### ISSUE TITLE
Output of btrfs-subvolumes.py contans 2 first lines with empty path and bad last line

### ISSUE THREAD

**Issue by MurzNN** [stecman/btrfs-df#2]
On my setup `btrfs-subvolumes.py` script shows more than one line with empty path field:
````
# btrfs-subvolumes.py /btrfs-mount
path                                                             qgroupid         rfer         excl 
----                                                             --------         ----         ---- 
                                                                 0/5           0.00GiB      0.00GiB 
                                                                 0/257         0.00GiB      0.00GiB 
office-servers                                                   0/259         0.00GiB      0.00GiB 
remote-servers                                                   0/260         0.00GiB      0.00GiB 
temp                                                             0/261         0.00GiB      0.00GiB 
.....
office-servers/srv/.snapshots                 0/7293        0.00GiB      0.00GiB 
office-servers/etc/.snapshots               0/7294        0.00GiB      0.00GiB 
office-servers/srv/.snapshots               
````
- so 2 first lines are empty, and last line don't contain numbers.

Empty path, as I understand, is root subvolume. But how filesystem can have 2 roots? And why is last line without numbers?

Also will be good to mark root subvolume via `<root>` text instead of empty line.

**Comment by stecman** [comment]
Thanks @MurzNN - I'd made a mistake in the changes from #1 that incorrectly started counting at line two (`------` underlines in the header) rather than the first line of data. Should probably get some tests sorted for this, but it's fixed in master now.

The blank lines are where there's no path found for a `qgroupid`. From what I can tell, these are dangling qgroups that haven't been cleaned up after a snapshot or subvolume is removed. I have a lot of these as I'm using `btrbk` which removes snapshots that aren't needed. Originally I had these printed as "???" as shown in the readme, though I'm reasonably confident they can be ignored now that I understand what they are.

**Comment by MurzNN** [comment]
Thanks for quick fixing, now seems work normally.

About blank lines - btrfs have issue with leaving qgroup after removing snapshot:  (https://btrfs.wiki.kernel.org/index.php/Quota_support -  After deleting a subvolume, you must manually delete the associated qgroup)

So I try to write script that cleanup them, based on output of your script. But in output of your script one blank line always exist, even if I delete them, so seems here is root subvolume. 

Will be good to detect qgroup for root subvolume and mark it as not-empty line.

**Comment by MurzNN** [comment]
Seems that the root subvolume always have id=5: 
https://btrfs.wiki.kernel.org/index.php/SysadminGuide

> Subvolumes are children of the top level subvolume (ID 5), typically directly below in the hierarchy or below some directories belonging to the top level subvolume, but especially not nested below other subvolumes

**Comment by MurzNN** [comment]
We can get root btrfs subvolume id via command `btrfs subvolume show <root btrfs volume path>` in string `Subvolume ID`, compare them with output of empty paths, and write `<root>` mark for needed line.
